#!/bin/sh
#
# /etc/init.d/opencp
# Subsystem file for "OpenLISP control-plane" server
#
# description: OpenLISP control-plane server daemon
#
# processname: OpenLISP
# config: /etc/opencp.conf
# config: /etc/opencp_*.xml
# pidfile: /var/run/opencp.pid

# source function library
#. /etc/rc.d/init.d/functions
. /lib/lsb/init-functions

# pull in sysconfig settings
[ -f /etc/opencp.conf ] && .

RETVAL=0
prog="opencp"

start() {
        echo -n "Starting $prog:"
        /sbin/opencp -f /etc/opencp.conf -d
        RETVAL=$?
        [ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
        echo
}

stop() {
        echo -n "Stopping $prog:"
        killproc $prog -TERM
        RETVAL=$?
        [ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
        echo
}

reload() {
        echo -n "Reloading $prog:"
        killproc $prog -HUP
        RETVAL=$?
        echo
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        reload)
                reload
                ;;
        condrestart)
                if [ -f /var/lock/subsys/$prog ] ; then
                        stop
                        # avoid race
                        sleep 3
                        start
                fi
                ;;
        status)
                status $prog
                RETVAL=$?
                ;;
        *)      (10)
                echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
                RETVAL=1
esac
exit $RETVAL
