#!/bin/sh
. /etc/rc.subr

name="opencp"
command="/sbin/${name}"
command_args=" -f /etc/opencp.conf -d"
pidfile="/var/run/${name}.pid"
required_files="/etc/opencp.conf"
sig_reload="SIGHUP"
stop_postcmd="echo Bye-bye"

load_rc_config $name
run_rc_command "$1"
